### ISSUE TITLE
flask_util.RegexConverter hangs on werkzeug 2.2.0 with some regexps

### ISSUE THREAD

**Issue by snarfed** [snarfed/webutil#8]
Example: `([^/:]+\.[^/:]+)`

Repro:

```py
app = Flask(__name__)
app.url_map.converters['regex'] = flask_util.RegexConverter
app.add_url_rule(r'/acct:<regex("([^/:]+\.[^/:]+)"):foo>', view_func=lambda: 'foo')
```

Pegs the CPU at 100%, probably an infinite loop in werkzeug 2.2.0's new router, pallets/werkzeug#2433 . It gets stuck parsing the rule, eg:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../flask/scaffold.py", line 56, in wrapper_func
    return f(self, *args, **kwargs)
  File ".../flask/app.py", line 1086, in add_url_rule
    self.url_map.add(rule)
  File ".../werkzeug/routing/map.py", line 174, in add
    rule.bind(self)
  File ".../werkzeug/routing/rules.py", line 554, in bind
    self.compile()
  File ".../werkzeug/routing/rules.py", line 655, in compile
    self._parts.extend(self._parse_rule(rule))
  File ".../werkzeug/routing/rules.py", line 590, in _parse_rule
    match = _part_re.match(rule, pos, endpos)
```

**Comment by snarfed** [comment]
Maybe related: pallets/werkzeug#2481

**Comment by snarfed** [comment]
They fixed it: https://github.com/pallets/werkzeug/issues/2481#issuecomment-1206228886
